Improvements from review
trikset/trik-models pull request #35
Opened 2021-03-12 00:50 UTC by khodand

- License
- Try to find a model in source dir
- Simple TRIK script example
- Detach `main()` and `if __name__ == '__main__':`

2021-03-13 11:37 UTC, iakov requested changes

2021-03-13 11:37 UTC, iakov commented on lobeClient/desktopClient.py
> +MODEL_PATH = sys.path[0]
`path.dirname(__file__)`? Или `path[0]` всё-таки?

2021-03-13 11:37 UTC, iakov commented on lobeClient/desktopClient.py
> +      script.wait(1000)
А зачем ожидание, если recieve есть блокирующий?

2021-03-15 10:30 UTC, khodand commented on lobeClient/desktopClient.py
> +MODEL_PATH = sys.path[0]
Если `path.dirname(__file__)`, то тогда при интерпретации не будет работать

2021-03-15 10:31 UTC, khodand commented on lobeClient/desktopClient.py
> +      script.wait(1000)
```suggestion
```

2021-03-19 16:23 UTC, iakov approved these changes

2021-03-19 16:23 UTC, merged